// Generated by the GopherC bind tool.
// 2019-04-05 09:24:03.2543584 +0200 CEST m=+0.005002301

// +build goc

package bind

func gocPutc(ch int32) int32

// Putc prints a character on the screen.
func Putc(ch int) int {
	_ch := int32(ch)
	_r := gocPutc(_ch)
	return int(_r)
}

