// Generated by the GopherC bind tool.
// 2019-04-04 21:55:26.7826638 +0200 CEST m=+0.009002101

// +build goc

package bind

func gocPutc(ch ) 

// Putc prints a character on the screen.
func Putc(ch )  {
	_ch := ch
	_r := gocPutc(_ch)
	return _r
}

